#!/usr/bin/env php
<?php

function usage() {
	global $argv;

	printf("usage: %s <host:port>", $argv[0]);
	exit(1);
}

function err(string $msg) {
	printf("error: %s\n", $msg);
	exit(1);
}

function valid_request($req): bool {
	if (!$req) return false;

	if (!isset($req['method']) || $req['method'] !== 'isPrime') {
		return false;
	}

	return isset($req['number']) && is_numeric($req['number']);

}

function response($req): string {
	return json_encode(['method' => 'isPrime', 'prime' => is_prime($req['number'])]);
}

function is_prime($n): bool {
	if ($n <= 1) return false;

	for ($i = 2; ($i * $i) <= $n; $i += 1) {
		if (($n % $i) === 0) {
			return false;
		}
	}

	return true;
}

function handle_conn($conn, ?string $peer_name) {
	printf("%s> connection accepted\n", $peer_name);

	while ($request = stream_get_line($conn, 0, "\n")) {
		if (strlen($request) === 0)  {
			break;
		}

		printf("%s> --> %s\n", $peer_name, $request);
		$json_request = json_decode($request, true);
		if (!valid_request($json_request)) {
			fwrite($conn, "\n");
			printf("%s> <-- malformed request\n", $peer_name);
			break;
		}
		$resp = response($json_request);
		printf("%s> <-- %s\n", $peer_name, $resp);
		fwrite($conn, $resp . "\n");
	}

	printf("%s> connection closed\n", $peer_name);
}

function fork_fn(callable $fn, ...$fn_args) {
	$pid = pcntl_fork();
	if ($pid === -1) {
		err("failed to fork");
	}
	if ($pid === 0) {
		call_user_func($fn, ...$fn_args);
		exit();
	}
}

function main() {
	global $argv;

	if (count($argv) < 2) {
		usage();
	}

	$socket = stream_socket_server(sprintf("tcp://%s", $argv[1]), $error_code, $error_message);
	if (!$socket) {
		err(sprintf("%s - %s", $error_code, $error_message));
	}
	printf("listening on %s\n", $argv[1]);

	while ($conn = stream_socket_accept($socket, null, $peer_name)) {
		if ($conn === false) {
			err("failed to accept connection");
		}

		fork_fn('handle_conn', $conn, $peer_name);

		fclose($conn);
	}

	while (pcntl_waitpid(0, $status) != 1);
	fclose($socket, STREAM_SHUT_RDWR);
}
main();
